name: intelligent-email-service
services:
    # --- Production Service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: intelligent_email_service_prod
    environment:
      - PYTHONUNBUFFERED = 1
      - APP_ENV = test_prod
      - EMAIL_PROVIDER=microsoft
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:-}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:-}
      - GRAPH_API_BASE_URL=${GRAPH_API_BASE_URL:-https://graph.microsoft.com/v1.0}
    env_file:
      - .env.test_prod
    volumes:
      - ./compressed_threads.json:/app/compressed_threads.json
  # --- Development Service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: intelligent_email_service_dev
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=dev
      - EMAIL_PROVIDER=mock
      - MOCK_SERVER_URL=${MOCK_SERVER_URL:-http://host.docker.internal:3000}
      - NVIDIA_API_KEY=${NVIDIA_API_KEY:-}
      - NVIDIA_MODEL=${NVIDIA_MODEL:-}
      - NVIDIA_BASE_URL=${NVIDIA_BASE_URL:-https://integrate.api.nvidia.com/v1}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.dev
    volumes:
      - ./compressed_threads.json:/app/compressed_threads.json
  